metadata_query = "Nc == {Nc} & Nt == {Nt} & Ns == {Ns} & beta == {beta} & nF == {nF} & mF == {mF}"
dir_template = "Sp{Nc}b{beta}nF{nF}mF{mF}T{Nt}L{Ns}"
plot_styles = "../styles/prd.mplstyle"
plot_filetype = "pdf"


include: "rules/gradient_flow.smk"
include: "rules/package.smk"
include: "rules/mpcac.smk"
include: "rules/mass.smk"
include: "rules/plaquette.smk"
include: "rules/combined_plots.smk"
include: "rules/spectrum_plots.smk"
include: "rules/spectrum_tables.smk"
include: "rules/extrapolation.smk"
include: "rules/csvs.smk"


topology_history_plots = [
    f"top_charge_history_{ensemble}"
    for ensemble in [
        "Sp4b6.9nF2mF-0.85T32L16",
        "Sp4b6.9nF2mF-0.87T32L16",
        "Sp4b6.9nF2mF-0.89T32L16",
        "Sp4b6.9nF2mF-0.91T32L16",
        "Sp4b6.9nF2mF-0.924T32L24",
        "Sp4b6.9nF2mF-0.92T32L24",
        "Sp4b6.9nF2mF-0.9T32L16",
        "Sp4b7.05nF2mF-0.835T36L20",
        "Sp4b7.05nF2mF-0.857T36L32",
        "Sp4b7.05nF2mF-0.85T36L24",
        "Sp4b7.05nF2mF-0.863T36L36",
        "Sp4b7.05nF2mF-0.867T36L36",
        "Sp4b7.2nF2mF-0.76T36L16",
        "Sp4b7.2nF2mF-0.77T36L24",
        "Sp4b7.2nF2mF-0.78T36L24",
        "Sp4b7.2nF2mF-0.794T36L28",
        "Sp4b7.2nF2mF-0.799T40L32",
        "Sp4b7.2nF2mF-0.79T36L24",
        "Sp4b7.2nF2mF-0.803T42L36",
        "Sp4b7.2nF2mF-0.808T48L36",
        "Sp4b7.2nF2mF-0.808T48L42",
        "Sp4b7.2nF2mF-0.813T48L36",
        "Sp4b7.4nF2mF-0.74T48L36",
        "Sp4b7.4nF2mF-0.755T48L42",
        "Sp4b7.4nF2mF-0.75T48L32",
        "Sp4b7.5nF2mF-0.71T48L36",
        "Sp4b7.5nF2mF-0.72T48L36",
    ]
]


plots_spectrum = expand(
    f"../assets/spectrum/plots/{{plot}}.{plot_filetype}",
    plot=[
        "w0_vs_mpcac",
        *topology_history_plots,
        "dec2_all_con_sp4fund",
        "m2_all_con_sp4fund",
        "mpsL",
        "Rvps_all_con_sp4fund",
        "spec_in_fps_summary_a2_am2_sp4fund",
        "spec_summary_a2_am2_sp4fund",
        "spec_in_fps_summary_a2_sp4fund",
        "spec_summary_a2_sp4fund",
    ],
)


tables_spectrum = expand(
    "../assets/spectrum/tables/{table}.tex",
    table=[
        "ensemble",
        "nlo_coefficients_decayconstant_a2",
        "nlo_coefficients_mass_a2",
        "nlo_coefficients_decayconstant_a2_am2",
        "nlo_coefficients_mass_a2_am2",
        "spectrum_meson_1",
        "spectrum_meson_2",
        "g_VPP_KSRF"
        ],
)

mass_lec_tables = expand(
    "../assets/spectrum/tables/le_coefficients_mass_ansatz_{ansatz}.tex",
    ansatz=["a", "a2", "m4", "a2_m4", "a2_am2", "full"],
)

decay_lec_tables = expand(
    "../assets/spectrum/tables/le_coefficients_decayconstant_ansatz_{ansatz}.tex",
    ansatz=["a", "a2", "m4", "a2_m4", "a2_am2", "full"],
)
extrapolation_mass_plots = expand(
    f"../assets/spectrum/plots/extrapolation_mass_ansatz_{{ansatz}}.{plot_filetype}",
    ansatz=["a", "a2", "m4", "a2_m4", "a2_am2", "full"]
)

extrapolation_decayconstant_plots = expand(
    f"../assets/spectrum/plots/extrapolation_decayconstant_ansatz_{{ansatz}}.{plot_filetype}",
    ansatz=["a", "a2", "m4", "a2_m4", "a2_am2", "full"]
)
extrapolation_by_meson = expand(
    f"../assets/spectrum/plots/{{obs}}_all_con_sp4fund.pdf",
    obs = ["m2", "dec2"]
)
nlo_tables = [
    "../assets/spectrum/tables/nlo_coefficients_decayconstant_a2_am2.tex",
    "../assets/spectrum/tables/nlo_coefficients_decayconstant_a2.tex",
    "../assets/spectrum/tables/nlo_coefficients_mass_a2_am2.tex",
    "../assets/spectrum/tables/nlo_coefficients_mass_a2.tex",
]

rule all:
    input:
        data=mass_lec_tables,
        decay_data=decay_lec_tables,
        mass_plots=extrapolation_mass_plots,
        decay_plots=extrapolation_decayconstant_plots,
        fit_plots=extrapolation_by_meson,
        nlo=nlo_tables,
        plots_spectrum=plots_spectrum,
        tables_spectrum=tables_spectrum,
