include: "rules/scattering.smk"

plots_scattering = [
    "../assets/scattering/plots/effective_masses_(g)evp.pdf",
    "../assets/scattering/plots/scattering/E_vs_L_heavy.pdf",
    "../assets/scattering/plots/scattering/E_vs_L_medium_light.pdf",
    "../assets/scattering/plots/scattering/phase_shift_plot_light.pdf",
    "../assets/scattering/plots/scattering/phase_shift_plot_medium.pdf",
    "../assets/scattering/plots/scattering/phase_shift_plot_heavy.pdf",
    "../assets/scattering/plots/scattering/sigma_comb_units.pdf",
    "../assets/scattering/plots/finite_volume/fv_b7.05_m0.867.pdf",
    "../assets/scattering/plots/finite_volume/fv_b7.05_m0.863.pdf",
    "../assets/scattering/plots/finite_volume/fv_b6.9_m0.92.pdf",
]

tables_scattering = [
    "../assets/scattering/tables/table_II.tex",
    "../assets/scattering/tables/beta6.9m-0.92.tex",
    "../assets/scattering/tables/beta7.05m-0.863.tex",
    "../assets/scattering/tables/beta7.05m-0.867.tex",
]

rule all:
    input:
        tables_scattering = tables_scattering,
        plots_scattering = plots_scattering,

